apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
  labels:
    app: chatbot-app
spec:
  # Pod의 복제본 수
  replicas: 1 
  selector:
    matchLabels:
      app: chatbot-app
  template:
    metadata:
      labels:
        app: chatbot-app
    spec:
      # Pod가 Harbor에서 이미지를 가져올 때 사용할 Secret을 지정합니다.
      # 이 섹션은 spec: 바로 아래에 위치해야 합니다.
      imagePullSecrets:
      - name: regcred 
      containers:
      - name: chatbot-app
        # Jenkins Pipeline이 업데이트한 최종 이미지 태그
        image: 192.168.1.18/library/chatbot-model:202512170651
        ports:
        - containerPort: 5000 # 챗봇 애플리케이션 포트
