apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
  namespace: chatbot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-app
  template:
    metadata:
      labels:
        app: chatbot-app
    spec:
      containers:
        - name: chatbot-app
          image: 192.168.1.18/chatbot/chatbot-app:v2
          ports:
            - containerPort: 5000

