apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  # --- 이 부분을 수정해야 합니다. ---
  namespace: chatbot # chatbot-prod 대신 chatbot으로 변경
spec:
  type: NodePort
  selector:
    app: chatbot-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
