apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: chatbot-prod
spec:
  type: NodePort
  selector:
    app: chatbot-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080

