apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: chatbot
  labels:
    app: chatbot-app
spec:
  type: NodePort
  selector:
    app: chatbot-app
  ports:
    - port: 5000  # 컨테이너 포트와 동일하게 설정
      targetPort: 5000
      nodePort: 30080 # 외부 접근 포트
      protocol: TCP
      name: http
